version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/trip-planner-api

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:

  BeforeInstall:
    - location: .aws/scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: .aws/scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: .aws/scripts/app_start.sh
      timeout: 300
      runas: root
