version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Installing dependencies
      - npm install
artifacts:
  files:
    - src/**/*
    - .aws/**/*
    - appspec.yml
    - package.json
